<a href="https://colab.research.google.com/github/GHAUTHAM2509/data_analytics_da/blob/main/23BCE0487.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("https://raw.githubusercontent.com/salemprakash/EDA/main/Data/Auto.csv")
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [ ]:
df["fuelEfficiency"] = df["mpg"] / df["cylinders"]
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name,fuelEfficiency
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,2.250
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,1.875
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,2.250
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,2.000
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,2.125
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500,1.875
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala,1.750
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii,1.750
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina,1.750
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl,1.875

In [ ]:
df["year"].value_counts()

year
73    40
78    36
76    34
75    30
82    30
70    29
79    29
72    28
77    28
81    28
71    27
80    27
74    26
Name: count, dtype: int64

In [ ]:
df["cylinders"].value_counts()

cylinders
4    199
8    103
6     83
3      4
5      3
Name: count, dtype: int64

In [ ]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,fuelEfficiency
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531,5.024605
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518,2.665723
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,1.125000
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000,2.496875
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000,5.250000
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000,7.250000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,11.650000

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
387    False
388    False
389    False
390    False
391    False
Length: 392, dtype: bool

In [ ]:
df.isnull().sum()

mpg               0
cylinders         0
displacement      0
horsepower        0
weight            0
acceleration      0
year              0
origin            0
name              0
fuelEfficiency    0
dtype: int64

In [ ]:
df_temp = df.drop('name', axis = 1)
df_temp.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,fuelEfficiency
0,18.0,8,307.0,130,3504,12.0,70,1,2.250
1,15.0,8,350.0,165,3693,11.5,70,1,1.875
2,18.0,8,318.0,150,3436,11.0,70,1,2.250
3,16.0,8,304.0,150,3433,12.0,70,1,2.000
4,17.0,8,302.0,140,3449,10.5,70,1,2.125

In [ ]:
df_temp.mean()

mpg                 23.445918
cylinders            5.471939
displacement       194.411990
horsepower         104.469388
weight            2977.584184
acceleration        15.541327
year                75.979592
origin               1.576531
fuelEfficiency       5.024605
dtype: float64

In [10]:
# example of binning
mpg_bin = pd.cut(df['mpg'],bins = 5)
mpg_bin.value_counts()

mpg
(16.52, 24.04]    131
(24.04, 31.56]    101
(8.962, 16.52]     91
(31.56, 39.08]     59
(39.08, 46.6]      10
Name: count, dtype: int64

In [21]:
#outlier detection in weight
weight = df['weight'].mean() + 2*df['weight'].std()
weight

4676.389303759368

In [22]:
df[df['weight']> 4676.389303759368]

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
41,12.0,8,383.0,180,4955,11.5,71,1,dodge monaco (sw)
42,13.0,8,400.0,170,4746,12.0,71,1,ford country squire (sw)
43,13.0,8,400.0,175,5140,12.0,71,1,pontiac safari (sw)
89,12.0,8,429.0,198,4952,11.5,73,1,mercury marquis brougham
93,13.0,8,440.0,215,4735,11.0,73,1,chrysler new yorker brougham
94,12.0,8,455.0,225,4951,11.0,73,1,buick electra 225 custom
102,11.0,8,400.0,150,4997,14.0,73,1,chevrolet impala
103,12.0,8,400.0,167,4906,12.5,73,1,ford country
135,13.0,8,350.0,150,4699,14.5,74,1,buick century luxus (sw)